steps:
- name: 'https://github.com/Event-U/front-end-master'
  args:
  - cp
  - ${_PRODUCTION_CONFIG}
  - production.yml
- name: 'https://github.com/Event-U/front-end-master'
  args:
  - install
- name: 'https://github.com/Event-U/front-end-master'
  args:
  - run
  - lint
- name: 'https://github.com/Event-U/front-end-master'
  args:
  - run
  - test
- name: 'https://github.com/Event-U/front-end-master'
  args:
  - run
  - build
- name: 'https://github.com/Event-U/front-end-master'
  args:
  - run
  - generate
- name: 'https://github.com/Event-U/front-end-master'
  args:
  - cp
  - ${_APP_YAML_CONFIG}
  - app.yaml
- name: 'https://github.com/Event-U/front-end-master'
  args:
  - app
  - deploy
  - --no-promote
timeout: '600s'